name: Create PR from weblate to Main

on:
  push:
    branches:
      - weblate

jobs:
  create_pr:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Create PR
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
        git fetch origin main:main
        git checkout main
        git merge --no-ff --no-commit weblate
        git commit -m "合并 weblate 更新至 main"
        git push origin main
