name: Weblate PR

on:
  push:
    branches:
      - weblate

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: '✅ 自动同步 - Weblate'
          branch: weblate
          base: main
          body: |
            这是一个由 GitHub Actions 自动创建的 PR，用于将 weblate 分支的变更合并到 main 分支。
            请审查并合并。
